[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "eleventy"
  command = "eleventy --serve"

[[redirects]]
  from = "/no-access/index.html"
  to = "/no-access/index.html"
  status = 200
